"""Seed lc_scoutskill with the two starter rows.

Upsert by lc_name. Both rows carry the full skill body in lc_instructions.
The thin on-disk bootstrap reads these at runtime.

Rows:
  1. daily-launch-report       (ports the existing v1 file-skill body)
  2. pre-meeting-launch-brief  (new headline behavior: Ep-7 demo)
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from scripts.auth import get_credential, load_env  # noqa: E402
from PowerPlatform.Dataverse.client import DataverseClient  # noqa: E402

TABLE = "lc_scoutskill"

# OutputFormat option-set values defined in build_lc_scoutskill.py
OF_TEAMS_HTML = 10600901


DAILY_LAUNCH_REPORT_INSTRUCTIONS = """\
Generate a daily LaunchControl launch report from Dataverse via the Launch
Control MCP server and DM it to the signed-in user in Teams.

MANDATORY: use the Launch Control MCP server for every data fetch. Do NOT
shell out to Python. Do NOT read files from disk. If the MCP server is
unavailable, abort and tell the user.

1. PULL THE DATA (sequential MCP read_query calls: parallel MCP calls time
   out):
   - SELECT lc_launchid, lc_name, lc_launchstatus, lc_targetdate
     FROM lc_launch WHERE statecode = 0
   - SELECT lc_milestoneid, lc_name, lc_milestonestatus, lc_launchid
     FROM lc_milestone WHERE statecode = 0
   - SELECT lc_taskid, lc_title, lc_taskstatus, lc_isblocked,
            lc_blockerreason, lc_milestoneid
     FROM lc_task WHERE statecode = 0
   - SELECT lc_title, lc_summary, lc_postedat, lc_launchid
     FROM lc_statusupdate WHERE statecode = 0

   Schema notes:
   - lc_launchstatus: OnTrack | AtRisk | Blocked | Slipped | Shipped
   - lc_milestonestatus: Planned | InProgress | Complete | AtRisk | Blocked
   - lc_taskstatus: NotStarted | InProgress | Done | Blocked
   - A task is blocked if lc_isblocked OR lc_taskstatus='Blocked'.
   - Tasks roll up to launches via milestones: task.lc_milestoneid ->
     milestone.lc_launchid.

2. ASSEMBLE AS HTML (Teams collapses raw Markdown newlines):
   <h2>🚀 LaunchControl daily report: <today></h2>
   <p><i><N> launches · <M> milestones · <K> open tasks</i></p>
   <h3><roll-up-emoji> <launch name></h3>
   <ul>
     <li><b>Target date:</b> <Mon DD or '-'></li>
     <li><b>Launch status:</b> <formatted></li>
     <li><b>Milestones (<n>):</b> <emoji> <status>: <n> · ...</li>
     <li><b>Open tasks (<n>):</b> <emoji> <status>: <n> · ...</li>
     <li><b>🔴 Blocked tasks (<n>):</b><ul><li><b><title></b>: <reason></li></ul></li>
     <li><b>Last status update (<Mon DD>):</b> <title></li>
   </ul>
   <blockquote><summary, truncated 280 chars></blockquote>
   <!-- repeat per launch -->
   <p><sub><i>Generated by Scout via Launch Control MCP</i></sub></p>

   Emoji: ⚪ Planned/NotStarted · 🔵 InProgress · 🟢 Complete/Done · 🟡 AtRisk · 🔴 Blocked
   Launch roll-up: 🔴 if any Blocked/Slipped · 🟡 if any AtRisk · else 🟢
   Sort launches by lc_targetdate asc, nulls last.

3. SEND VIA m365_teams_send_chat_message to the signed-in user. If the tool
   exposes contentType/bodyType, set to html; otherwise prepend
   <html><body>...</body></html>.

4. REPLY in Scout with exactly one line:
   ✅ Sent today's launch report to your Teams. <N> launch(es), <M> blocked task(s).
"""


PRE_MEETING_LAUNCH_BRIEF_INSTRUCTIONS = """\
Assemble a pre-meeting briefing pack for an upcoming launch review and DM
it to the signed-in user in Teams.

MANDATORY: use the Launch Control MCP server for Dataverse reads. Do NOT
shell out. Do NOT read repo files.

1. RESOLVE TARGET LAUNCH
   - If the user's message contains a launch name, use it.
   - Else find the next M365 calendar event in the next 4 hours whose
     subject contains 'launch' or matches an lc_launch.lc_name value;
     use that launch.
   - If no launch can be resolved, ask the user which launch to brief on
     and stop.

2. GATHER DATAVERSE FACTS (sequential MCP read_query):
   - The launch row:
     SELECT lc_launchid, lc_name, lc_launchstatus, lc_targetdate,
            lc_description
     FROM lc_launch
     WHERE lc_name = '<resolved name>' AND statecode = 0
   - Its milestones:
     SELECT lc_milestoneid, lc_name, lc_milestonestatus, lc_duedate
     FROM lc_milestone
     WHERE lc_launchid = '<launchid>' AND statecode = 0
   - All tasks under those milestones (one query per milestone is fine):
     SELECT lc_taskid, lc_title, lc_taskstatus, lc_isblocked,
            lc_blockerreason, lc_duedate, lc_milestoneid
     FROM lc_task
     WHERE lc_milestoneid IN (<milestone ids>) AND statecode = 0
   - Most recent status update for the launch:
     SELECT TOP 1 lc_title, lc_summary, lc_postedat
     FROM lc_statusupdate
     WHERE lc_launchid = '<launchid>' AND statecode = 0
     ORDER BY lc_postedat DESC

3. INVOKE THE AI PROMPT lc_DraftLaunchBriefing (Custom API from Ep 5)
   - Preferred path: shell out to the Python bridge
       python scripts/fire_draft_briefing.py "<launch name>"
     from the launch-control repo (cwd: the repo root). Capture stdout as
     'ai_talking_points'. The bridge POSTs to the unbound Custom Action
     /api/data/v9.2/lc_DraftLaunchBriefing.
   - If the bridge exits non-zero (typical cause: 404: the Custom Action
     wasn't registered in this env yet), set ai_talking_points to:
       'AI talking points unavailable: lc_DraftLaunchBriefing Custom Action
        is not registered in this environment. Run
        `python scripts/register_ai_prompt.py prompts/DraftLaunchBriefing`
        from the repo root to deploy Ep-5 Part 4, then retry.'
     and continue assembling the rest of the pack.
   - If the Dataverse MCP server later exposes a Custom Action invocation
     tool (e.g. execute_unbound_action), prefer that over the shell path.

4. ASSEMBLE BRIEFING PACK AS HTML (Teams renders HTML, not Markdown):
   <h2>📋 Briefing: <launch name></h2>
   <p><i>For your upcoming review · <meeting time if known></i></p>

   <h3>🚦 At a glance</h3>
   <ul>
     <li><b>Launch status:</b> <roll-up emoji> <formatted></li>
     <li><b>Target date:</b> <Mon DD or '-'></li>
     <li><b>Milestones:</b> <n> total · <breakdown by status></li>
     <li><b>Open tasks:</b> <n> total · <breakdown></li>
     <li><b>Blocked tasks:</b> <n><ul>...</ul></li>
   </ul>

   <h3>🤖 AI-drafted talking points</h3>
   <blockquote><ai_talking_points (HTML-escape, preserve paragraphs)></blockquote>

   <h3>❓ Suggested questions to raise</h3>
   <ul>
     <li>One question per identified blocker (mention the blocker by title).</li>
     <li>If any milestone is AtRisk: 'What would it take to move <milestone> back to InProgress before the launch date?'</li>
     <li>If the most recent status update is older than 5 days: 'When was the last formal status update? The latest in Dataverse is from <date>.'</li>
   </ul>

   <p><sub><i>Generated by Scout via Launch Control MCP · registry row: pre-meeting-launch-brief</i></sub></p>

   Roll-up: 🔴 Blocked/Slipped · 🟡 AtRisk · 🟢 OnTrack/Shipped.

5. SEND VIA m365_teams_send_chat_message to the signed-in user (DM-to-self
   is the default demo target). If the user explicitly says 'post to the
   meeting chat', resolve the chat by meeting subject and post there
   instead. If the tool exposes contentType/bodyType, set to html;
   otherwise prepend <html><body>...</body></html>.

6. REPLY in Scout with exactly one line:
   ✅ Briefing for <launch> sent to your Teams. <N> blockers, <M> AtRisk milestones.

FAILURE HANDLING
- MCP signed-out / token expired: tell the user to re-add the Launch
  Control MCP server in Scout, and do NOT send the Teams DM.
- m365_teams_send_chat_message fails: retry once; on second failure,
  surface the full error and offer to copy the HTML to clipboard.
"""


ROWS = [
    {
        "lc_name": "daily-launch-report",
        "lc_description": "Daily LaunchControl launch report DM'd to the signed-in user in Teams. Triggers: 'daily launch report', 'launch report', 'daily standup'.",
        "lc_trigger": "daily launch report, launch report, daily standup, daily report, status of all launches",
        "lc_instructions": DAILY_LAUNCH_REPORT_INSTRUCTIONS,
        "lc_outputformat": OF_TEAMS_HTML,
    },
    {
        "lc_name": "pre-meeting-launch-brief",
        "lc_description": "Pre-meeting briefing pack for an upcoming launch review (status + AI talking points + suggested questions) DM'd in Teams. Triggers: 'brief me on <launch>', 'pre-meeting briefing'.",
        "lc_trigger": "brief me on, briefing on, pre-meeting briefing, prep me for, launch briefing, brief me, briefing pack",
        "lc_instructions": PRE_MEETING_LAUNCH_BRIEF_INSTRUCTIONS,
        "lc_outputformat": OF_TEAMS_HTML,
    },
]


def upsert_row(client, row):
    pages = client.records.get(
        "lc_scoutskill",
        filter=f"lc_name eq '{row['lc_name']}'",
        select=["lc_scoutskillid"],
        top=1,
    )
    existing = next((r for page in pages for r in page), None)
    if existing:
        client.records.update("lc_scoutskill", existing["lc_scoutskillid"], row)
        print(f"  ~ updated {row['lc_name']}")
    else:
        rid = client.records.create("lc_scoutskill", row)
        print(f"  + created {row['lc_name']} ({rid})")


def main():
    load_env()
    env_url = os.environ["DATAVERSE_URL"].rstrip("/")
    print(f"Target env: {env_url}")
    cred = get_credential()
    client = DataverseClient(env_url, cred)
    print("Seeding lc_scoutskill rows ...")
    for row in ROWS:
        upsert_row(client, row)
    print("Done.")


if __name__ == "__main__":
    main()
